"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [
	{ on = [ "j" ], run = "leave" },
	{ on = [ "l" ], run = "arrow -1" },
	{ on = [ "k" ], run = "arrow 1" },
	{ on = [ ";" ], run = "enter" },
]
