"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
linemode    = "size"
show_hidden = true
sort_by     = "natural"

[preview]
tab_size   = 2
max_width  = 1000
max_height = 1000

[plugin]
previewers = [
  { name = "*/", run = "folder", sync = true },
  { name = "*.md", run = "preview" },
  { name = "*.csv", run = "preview" },
  { mime = "text/*", run = "code" },
  { mime = "*/xml", run = "code" },
  { mime = "*/javascript", run = "code" },
  { mime = "*/x-wine-extension-ini", run = "code" },
  { name = "*", run = "preview" },
]
