local g = vim.g
local o = vim.o
local opt = vim.opt

g.nord_borders = true
g.nord_italic = false
g.nord_uniform_diff_background = true
g.r_indent_align_args = 0
g.tmux_navigator_no_wrap = 1
o.ignorecase = false
o.termguicolors = true
o.timeout = true
o.timeoutlen = 500
opt.autoindent = true
opt.backup = false
opt.clipboard = "unnamedplus"
opt.conceallevel = 3
opt.expandtab = true
opt.incsearch = true
opt.number = true
opt.relativenumber = true
opt.shiftwidth = 2
opt.smartindent = true
opt.softtabstop = 2
opt.swapfile = false
opt.tabstop = 2
opt.undofile = true
opt.undolevels = 10000
opt.updatetime = 50
opt.iskeyword:append("-")
